### ISSUE TITLE
total energy and gas settings are not updated (2) - request for enhancement

### ISSUE THREAD

**Issue by BOverdevest** [StefanPostma/n.vinceste.open-toon#10]
Hi Stefan

I had the same issue with P1 values not updating (referring to the closed issue with similar).
I changed the dev_2.x --> dev_4.x in devices.js and re-installed. and everything worked

Would it be possible to make this change in the advanced settings.
Using  [http://<TOON-IP>/hdrv_zwave?action=getDevices.json] people could quickly see it they need a 2, 3 or 4.
Maybe this could even be automated during initialisation?

PS: there is an error on line 300: the logging should be "Update Power Usage"
			_// Check for power usage information
			if (dataRootObject.hasOwnProperty('dev_2.4') || dataRootObject.hasOwnProperty('dev_2.6')) {
				this.log ('**Update gas usage**')
			 	this._processPowerUsageData(dataRootObject);_

**Comment by StefanPostma** [comment]
know issues has to do with different Id's from the smart meters
