### ISSUE TITLE
Replace Gas meter with Gas Usage on ToonDevice Dashboard

### ISSUE THREAD

**Issue by BOverdevest** [StefanPostma/n.vinceste.open-toon#11]
Stefan

The ToonDevice Dashboard shows Gasmeter on the bottom right (together with 'stroom meterstand piek' stroom meterstand dal" and " energie")

Would it be an enhancement to replace the Gasmeter with Gas Usage which is also available in 
http://<Toon-IP./happ_pwrusage?action=GetCurrentUsage
_{"result":"ok",
"powerUsage": {"value":460, "avgValue":432.22},
"powerProduction": {"value":0, "avgValue":0.00},
"gasUsage": {"value":9, "avgValue":19.16}
}_
As i read it at the moment of copying my usage according to TOON (P1 meter) is 9 liter per hour.
the Gas meter could still be available as a tag data point.

**Comment by RoadXY** [comment]
gasUsage is an problem: it isn't provided on every Toon (in fact, most wont)
