### ISSUE TITLE
Add app to community store

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [StefanPostma/n.vinceste.open-toon#17]
Perhaps it's an idea to add this app to the homey community store so people can easily install it?

**Comment by BOverdevest** [comment]
indeed, that would be a great idea

**Comment by yustmenl** [comment]
Agree it would be Nice to have in the store!

**Comment by StefanPostma** [comment]
will investigate, because it's a fork of the original Toon App i am not sure if it will raise issues

**Comment by BOverdevest** [comment]
The HCS is made especially for Homey app that are in competition / conflict with official app/partners.
The owner mentioned earlier on the community forum, that you are more than welcome

**Comment by StefanPostma** [comment]
Hi Team, i investigated the possibilities of putting this on the Homey Store. It's not possible without a lot of re-writing the code as packages names between this and the original Toon app is shared. This could cause conflicts. Besides that issue, its not build on the New App V2 libraries yet so does not comply with the latest homey standards
