### ISSUE TITLE
Including boiler values

### ISSUE THREAD

**Issue by StefanPostma** [StefanPostma/n.vinceste.open-toon#2]
next up: including extra boiler values into Homey:

http://ToonIP/boilerstatus/boilervalues.txt

boilerPressure
boilerOutTemp
boilerInTemp
boilerModulationLevel

**Comment by BOverdevest** [comment]
Hi @StefanPostma . 
any progress on this. This would indeed make a very nice addition, to be able to set  an alarm to the user when pressure is too low.
I see some script  was shared here: [https://community.athom.com/t/stoom-gas-verbruik-uitlezen-rooted-toon/16414/3](url)

**Comment by StefanPostma** [comment]
Hey Bart, Zeker een optie, helaas zit ik in het buitenland op het moment en heb ik dus mijn toon niet aan de muur hangen :)
Ik ga er rond september mee aan de slag. Bedankt voor het delen van de link!

Mocht je zelf willen proberen maak vooral een fork, ik zal de code samenvoegen en testen zodra ik terug ben.

**Comment by BOverdevest** [comment]
Hi Stefan
Al vorderingen hiermee? Het zou je homey app helemaal afmaken. 
ik heb zelf geen skills om dit aan te pakken, heb er wel naar zitten staren.
Bart

**Comment by BOverdevest** [comment]
Helaas zijn boilerOutTemp / boilerInTemp niet meer beschikbaar in BoilerText.
